/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-21 13:04:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_002duser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Add User", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- Include Lottie Animation -->\n");
      out.write("<script src=\"https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs\" type=\"module\"></script>\n");
      out.write("\n");
      out.write("<!-- Play Lottie Animation -->\n");
      out.write("<div class=\"flex justify-center mb-6\">\n");
      out.write("	<dotlottie-player src=\"https://lottie.host/5eda3539-6411-404d-b70b-097f7ca70bed/IzVBXhxTXj.json\" \n");
      out.write("		background=\"transparent\" speed=\"1\" style=\"width: 300px; height: 300px;\" loop autoplay>\n");
      out.write("	</dotlottie-player>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"flex justify-center\">\n");
      out.write("	<form class=\"w-full max-w-lg\" action=\"/add-user\" method=\"post\">\n");
      out.write("	\n");
      out.write("		<!-- First Name  &  Last Name -->\n");
      out.write("		<div class=\"flex flex-wrap -mx-3 mb-6\">\n");
      out.write("			<div class=\"w-full md:w-1/2 px-3 mb-6 md:mb-0\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-first-name\">\n");
      out.write("				First Name\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white\" \n");
      out.write("				       id=\"grid-first-name\" type=\"text\" placeholder=\"Jane\" name=\"fname\" required minlength = \"2\" maxlength = \"50\">\n");
      out.write("				<p class=\"text-red-500 text-xs italic\">Please fill out this field (2-50 characters).</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w-full md:w-1/2 px-3\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-last-name\">\n");
      out.write("				Last Name\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-last-name\" type=\"text\" placeholder=\"Doe\" name=\"lname\" required>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Email -->\n");
      out.write("		<div class=\"flex flex-wrap -mx-3 mb-6\">\n");
      out.write("			<div class=\"w-full px-3\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-email\">\n");
      out.write("				Email\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-email\" type=\"email\" placeholder=\"user@gmail.com\" name=\"email\" required>\n");
      out.write("				<p class=\"text-red-500 text-xs italic\">Please fill out this field.</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Password  &  Retype Password-->\n");
      out.write("		<div class=\"flex flex-wrap -mx-3 mb-6\">\n");
      out.write("			<div class=\"w-full md:w-1/2 px-3 mb-6 md:mb-0\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-password\">\n");
      out.write("				Password\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white\" \n");
      out.write("				       id=\"grid-password\" type=\"password\" placeholder=\"******************\" name=\"password\" required >\n");
      out.write("				<p class=\"text-gray-600 text-xs italic\">Make it as long and as crazy as you'd like</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w-full md:w-1/2 px-3\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-repassword\">\n");
      out.write("				Retype Password\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-repassword\" type=\"password\" placeholder=\"******************\" name=\"re-password\" required>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Mobile &  Address & NIC-->\n");
      out.write("		<div class=\"flex flex-wrap -mx-3 mb-2\">\n");
      out.write("			<div class=\"w-full md:w-1/3 px-3 mb-6 md:mb-0\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-mobile\">\n");
      out.write("				Mobile\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-mobile\" type=\"number\" placeholder=\"07xxxxxxxx\" name=\"mobile\" required>\n");
      out.write("				<p class=\"text-gray-600 text-xs italic\">Please enter a valid mobile number (10 digits)</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w-full md:w-1/3 px-3 mb-6 md:mb-0\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-address\">\n");
      out.write("				Address\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-address\" type=\"text\" placeholder=\"Colombo\" name=\"address\" required>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w-full md:w-1/3 px-3 mb-6 md:mb-0\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-nic\">\n");
      out.write("				NIC\n");
      out.write("				</label>\n");
      out.write("				<input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("				       id=\"grid-nic\" type=\"text\" placeholder=\"98xxxxxxxV\" name=\"NIC\" required>\n");
      out.write("				<p class=\"text-red-500 text-xs italic\">Please enter a valid NIC (9 digits followed by V or v / 12 digits)</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Role -->\n");
      out.write("		<div class=\"flex flex-wrap -mx-3 mb-6\">\n");
      out.write("			<div class=\"w-full px-3\">\n");
      out.write("				<label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"grid-role\">\n");
      out.write("				Role\n");
      out.write("				</label>\n");
      out.write("				<div class=\"relative\">\n");
      out.write("					<select class=\"block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500\" \n");
      out.write("					        id=\"grid-role\" name=\"role\" required>\n");
      out.write("						<option value=\"event_manager\">Event Manager</option>\n");
      out.write("						<option value=\"attendee\">Attendee</option>\n");
      out.write("					</select>\n");
      out.write("					<div class=\"pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700\">\n");
      out.write("						<svg class=\"fill-current h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\">\n");
      out.write("							<path d=\"M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z\"/>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<button type=\"submit\" class=\"btn btn-primary block w-full border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white\">Sign Up</button>\n");
      out.write("		\n");
      out.write("		<p class=\"text-red-500 text-xs italic\">Already have an account?</p>\n");
      out.write("		<a class=\"btn btn-secondary btn-sm block w-full border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white\" href=\"/login\">Login</a>\n");
      out.write("	\n");
      out.write("	</form>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
