/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-18 09:23:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.message;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Contact Us", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- Inline CSS for Styling -->\n");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: Arial, sans-serif;\n");
      out.write("        background-color: #f0f4ff; /* Light background */\n");
      out.write("        margin: 0;\n");
      out.write("        padding: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    h1 {\n");
      out.write("        text-align: center;\n");
      out.write("        color: #3d43fb; /* Title color */\n");
      out.write("        margin-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-group {\n");
      out.write("        max-width: 500px; /* Limit form width */\n");
      out.write("        margin: 0 auto; /* Center the form */\n");
      out.write("        background-color: white; /* White background for form */\n");
      out.write("        border-radius: 8px; /* Rounded corners */\n");
      out.write("        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow */\n");
      out.write("        padding: 20px; /* Padding inside the form */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-group label {\n");
      out.write("        display: block; /* Labels on new lines */\n");
      out.write("        margin-bottom: 5px; /* Space between label and input */\n");
      out.write("        color: #333; /* Label color */\n");
      out.write("        font-weight: bold; /* Bold labels */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-control {\n");
      out.write("        width: 100%; /* Full width for inputs */\n");
      out.write("        padding: 10px; /* Padding inside inputs */\n");
      out.write("        margin-bottom: 15px; /* Space between inputs */\n");
      out.write("        border: 1px solid #ccc; /* Border for inputs */\n");
      out.write("        border-radius: 4px; /* Rounded corners for inputs */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-control:focus {\n");
      out.write("        border-color: #3d43fb; /* Border color on focus */\n");
      out.write("        box-shadow: 0 0 5px rgba(61, 67, 251, 0.5); /* Shadow on focus */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary {\n");
      out.write("        background-color: #007bff; /* Button color */\n");
      out.write("        color: white; /* Button text color */\n");
      out.write("        padding: 10px 20px; /* Button padding */\n");
      out.write("        border: none; /* No border */\n");
      out.write("        border-radius: 5px; /* Rounded corners for button */\n");
      out.write("        cursor: pointer; /* Pointer cursor on hover */\n");
      out.write("        font-size: 16px; /* Button text size */\n");
      out.write("        width: 100%; /* Full width button */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary:hover {\n");
      out.write("        background-color: #0056b3; /* Darker blue on hover */\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<h1 class=\"text-3xl font-bold mb-4\">Contact Us</h1>\n");
      out.write("\n");
      out.write("<form class=\"flex justify-center\" action=\"/contact-us\" method=\"post\">\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"name\">Name</label>\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Name\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"email\">Email</label>\n");
      out.write("        <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"subject\">Subject</label>\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"subject\" name=\"subject\" placeholder=\"Subject\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"message\">Message</label>\n");
      out.write("        <textarea class=\"form-control\" id=\"message\" name=\"message\" placeholder=\"Message\" rows=\"5\" required></textarea> <!-- Changed to textarea for better usability -->\n");
      out.write("        \n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">Submit</button>  \n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
