/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-18 09:11:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651833732000L));
    _jspx_dependants.put("jar:file:/D:/event/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OOP-Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Endless Events</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("    <!-- Ionicons script -->\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        /* Updated navbar with new colors */\n");
      out.write("        nav {\n");
      out.write("            background-color: #cddcfd; /* Background color */\n");
      out.write("        }\n");
      out.write("        nav a {\n");
      out.write("            color: #3d43fb; /* Font color */\n");
      out.write("        }\n");
      out.write("        nav a:hover {\n");
      out.write("            color: #fff; /* Font color on hover */\n");
      out.write("            background-color: #3d43fb; /* Background on hover */\n");
      out.write("        }\n");
      out.write("        /* Mobile menu button */\n");
      out.write("        .toggle-menu svg {\n");
      out.write("            fill: #3d43fb;\n");
      out.write("        }\n");
      out.write("        .toggle-menu svg:hover {\n");
      out.write("            fill: #fff;\n");
      out.write("        }\n");
      out.write("        /* Profile and icon colors */\n");
      out.write("        .dark:hover:text-green-300 {\n");
      out.write("            color: #3d43fb !important;\n");
      out.write("        }\n");
      out.write("        /* Announcement icon position */\n");
      out.write("        .announcement-icon {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 1rem; /* Adjust as needed */\n");
      out.write("            top: 50%; /* Center vertically */\n");
      out.write("            transform: translateY(-50%); /* Center the icon */\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"shadow fixed top-0 w-full z-10\">\n");
      out.write("        <div class=\"container px-6 py-3 mx-auto relative\"> <!-- Added 'relative' to the container -->\n");
      out.write("            <div class=\"md:flex md:items-center md:justify-between\">\n");
      out.write("                <div class=\"flex items-center justify-between\">\n");
      out.write("                    <div class=\"text-xl font-semibold\">\n");
      out.write("                        <a href=\"/\" class=\"flex items-center\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo.png\" alt=\"Endless Events Logo\" class=\"h-12\"> <!-- Logo Image -->\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Mobile menu button -->\n");
      out.write("                    <div class=\"flex md:hidden\">\n");
      out.write("                        <button type=\"button\" class=\"toggle-menu\" aria-label=\"toggle menu\">\n");
      out.write("                            <svg viewBox=\"0 0 24 24\" class=\"w-6 h-6\">\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2z\"></path>\n");
      out.write("                            </svg>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Mobile Menu open: \"block\", Menu closed: \"hidden\" -->\n");
      out.write("                <div class=\"flex-1 md:flex md:items-center md:justify-between hidden mobile-menu\">\n");
      out.write("                    <div class=\"flex flex-col -mx-4 md:flex-row md:items-center md:mx-8\">\n");
      out.write("                        <a href=\"/events\" class=\"px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb\">\n");
      out.write("                            <ion-icon name=\"calendar-outline\"></ion-icon> Events\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"/contact-us\" class=\"px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb\">\n");
      out.write("                            <ion-icon name=\"mail-outline\"></ion-icon> Contact Us\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"/categories\" class=\"px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb\">\n");
      out.write("                            <ion-icon name=\"list-outline\"></ion-icon> Categories\n");
      out.write("                        </a>\n");
      out.write("                        \n");
      out.write("                        <!-- Session Check for Login/Logout and Admin Panel -->\n");
      out.write("                        ");

                            String role = (String)session.getAttribute("role");

                            if(session.getAttribute("id") == null){
                                out.print("<a href='/login' class='px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb'>");
                                out.print("<ion-icon name='log-in-outline'></ion-icon> Login</a>");
                                out.print("<a href='/add-user' class='px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb'>");
                                out.print("<ion-icon name='person-add-outline'></ion-icon> Register</a>");
                            }
                            else if (role.equals("admin")) {
                                out.print("<a href='/dashboard' class='px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb'>");
                                out.print("<ion-icon name='settings-outline'></ion-icon> Admin Panel</a>");
                            }
                            else {
                                out.print("<a href='/dashboard' class='px-2 py-1 mx-2 mt-2 text-sm font-medium transition-colors duration-200 transform rounded-md md:mt-0 hover:text-white hover:bg-#3d43fb'>");
                                out.print("<ion-icon name='home-outline'></ion-icon> Dashboard</a>");
                            }
                        
      out.write("\n");
      out.write("                        \n");
      out.write("                        <!-- Profile and Logout -->\n");
      out.write("                        <div class=\"flex items-center mt-3 md:mt-0\">\n");
      out.write("                            ");

                                if(session.getAttribute("id") != null){
                                    out.print("<a class='mx-4 text-green-600 md:block dark:text-green-200 hover:text-green-700 dark:hover:text-green-400 focus:text-green-700 dark:focus:text-green-400 focus:outline-none' href='/logout'>");
                                    out.print("<ion-icon name='log-out-outline'></ion-icon></a>");

                                    out.print("<a href='/profile' class='flex items-center focus:outline-none' aria-label='toggle profile dropdown'>");
                                    out.print("    <div class='w-8 h-8 overflow-hidden border-2 border-green-400 rounded-full'>");
                                    out.print("        <img src='https://avatars.dicebear.com/api/micah/" + session.getAttribute("fname") +".svg' class='object-cover w-full h-full' alt='avatar'>");
                                    out.print("    </div>");
                                    out.print("    <h3 class='mx-2 text-sm font-medium text-green-700 dark:text-green-200'>" + session.getAttribute("fname") +"</h3>");
                                    out.print("</a>");
                                }
                            
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Announcement Icon Positioned at Right Corner -->\n");
      out.write("            <a href=\"/announcements\" class=\"announcement-icon\" aria-label=\"show notifications\">\n");
      out.write("                <ion-icon name=\"notifications-outline\" class=\"w-6 h-6 text-green-600 hover:text-green-700\"></ion-icon>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/header/nav.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
